### ISSUE TITLE
Choosing a sentinel

### ISSUE THREAD

**Issue by Nepoxx** [Vungle/simple-sentinel#2]
Having a way to customize how sentinels are chosen would be very useful. for instance, in a multi-region cluster, selecting the nearest (lowest latency/ping) sentinel would be preferable to picking a random one.

I see that there's a `randomizeSentinels` option which is a boolean, what does setting it to false do? ~~Does it simply pick the first one in the array?~~ Found my answer [here](https://github.com/Vungle/simple-sentinel/blob/8a172043d99c49bd77b9af310673a20a438b96dd/src/redisSentinel.js#L112)

**Comment by gootik** [comment]
@Nepoxx Unfortunately we are not maintaining this library anymore. But if you want to make a PR, it would be more than welcome :)
